import 'package:flutter/material.dart';
import 'package:http/http.dart' as http;
import 'dart:convert';
import '../data/models/song_model.dart';
import '../data/models/lyrics_model.dart';
import '../data/models/lyric_line_model.dart';
import '../data/services/lyrics_db_service.dart';
import '../data/services/character_converter.dart';
import '../data/services/pinyin_service.dart';
import '../data/constants.dart';

class AddSongDialog extends StatefulWidget {
  const AddSongDialog({super.key});

  @override
  State<AddSongDialog> createState() => _AddSongDialogState();
}

class _AddSongDialogState extends State<AddSongDialog> with SingleTickerProviderStateMixin {
  final _titleController = TextEditingController();
  final _artistController = TextEditingController();
  final _lyricsController = TextEditingController();
  late TabController _tabController;
  bool _isSearching = false;
  List<dynamic> _searchResults = [];
  String? _errorMessage;

  @override
  void initState() {
    super.initState();
    _tabController = TabController(length: 2, vsync: this);
  }

  @override
  void dispose() {
    _titleController.dispose();
    _artistController.dispose();
    _lyricsController.dispose();
    _tabController.dispose();
    super.dispose();
  }

  Future<void> _searchSong() async {
    if (_titleController.text.isEmpty) {
      setState(() {
        _errorMessage = 'Please enter a song title';
      });
      return;
    }

    setState(() {
      _isSearching = true;
      _errorMessage = null;
      _searchResults = [];
    });

    try {
      final searchQuery = _artistController.text.isEmpty
          ? _titleController.text
          : '${_titleController.text} ${_artistController.text}';

      final url = Uri.parse(
        'https://lrclib.net/api/search?q=${Uri.encodeComponent(searchQuery)}',
      );

      final response = await http.get(url);

      if (response.statusCode == 200) {
        final results = jsonDecode(response.body) as List;

        if (results.isEmpty) {
          setState(() {
            _errorMessage = 'No lyrics found. Try a different search.';
            _isSearching = false;
          });
        } else {
          setState(() {
            _searchResults = results;
            _isSearching = false;
          });
        }
      } else {
        setState(() {
          _errorMessage = 'Failed to search. Please try again.';
          _isSearching = false;
        });
      }
    } catch (e) {
      setState(() {
        _errorMessage = 'Error: $e';
        _isSearching = false;
      });
    }
  }

  Future<void> _addSong(dynamic result) async {
    final plainLyrics = result['plainLyrics'];

    if (plainLyrics == null || plainLyrics.toString().isEmpty) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text('No lyrics available for this song')),
      );
      return;
    }

    await _saveSong(
      result['trackName'] as String,
      (result['artistName'] as String?) ?? '',
      plainLyrics.toString(),
    );
  }

  Future<void> _addManualSong() async {
    if (_titleController.text.isEmpty || _lyricsController.text.isEmpty) {
      setState(() {
        _errorMessage = 'Please fill in song title and lyrics';
      });
      return;
    }

    await _saveSong(
      _titleController.text,
      _artistController.text,
      _lyricsController.text,
    );
  }

  Future<void> _saveSong(String title, String artist, String plainLyrics) async {
    // Convert to traditional Chinese (in case user pasted simplified)
    CharacterConverter.initialize();
    final traditionalTitle = CharacterConverter.toTraditional(title);
    final traditionalArtist = artist.isEmpty ? 'Unknown' : CharacterConverter.toTraditional(artist);
    final traditionalLyrics = CharacterConverter.toTraditional(plainLyrics);

    // Generate song ID
    final songId = artist.isEmpty
        ? traditionalTitle.toLowerCase().replaceAll(' ', '_')
        : '${traditionalTitle.toLowerCase().replaceAll(' ', '_')}_${traditionalArtist.toLowerCase().replaceAll(' ', '_')}';

    // Create song
    final now = DateTime.now();
    final song = Song(
      id: songId,
      title: traditionalTitle,
      author: traditionalArtist,
      addedDate: now,
      lastActivity: now,
    );

    // Process lyrics lines
    final lyricsLines = traditionalLyrics.split('\n');
    final lyricLinesList = <LyricLine>[];

    for (int i = 0; i < lyricsLines.length; i++) {
      final line = lyricsLines[i].trim();
      if (line.isEmpty) continue;

      lyricLinesList.add(LyricLine(
        lineNumber: i,
        traditionalChinese: line,
        pinyin: '', // Will be generated by the app
      ));
    }

    // Create lyrics
    final lyrics = Lyrics(
      songId: songId,
      lines: lyricLinesList,
    );

    // Save to database
    try {
      await LyricsDB.insertSong(song);
      await LyricsDB.insertLyrics(lyrics);

      // Generate pinyin in the background (fire and forget)
      _generatePinyinInBackground(songId, lyricLinesList);

      if (mounted) {
        Navigator.pop(context, true); // Return true to indicate success
        final message = artist.isEmpty
            ? 'Added "$title"'
            : 'Added "$title" by $artist';
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text(message)),
        );
      }
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text('Error adding song: $e')),
        );
      }
    }
  }

  /// Generate pinyin for all lines in the background
  void _generatePinyinInBackground(String songId, List<LyricLine> lines) {
    // Run asynchronously without awaiting
    Future.microtask(() async {
      try {
        final updatedLines = <LyricLine>[];

        for (final line in lines) {
          if (line.traditionalChinese.isNotEmpty) {
            // Generate pinyin for this line
            final pinyin = PinyinService.convertLine(line.traditionalChinese);

            updatedLines.add(LyricLine(
              lineNumber: line.lineNumber,
              traditionalChinese: line.traditionalChinese,
              pinyin: pinyin,
            ));
          } else {
            updatedLines.add(line);
          }
        }

        // Update database with generated pinyin
        final updatedLyrics = Lyrics(songId: songId, lines: updatedLines);
        await LyricsDB.insertLyrics(updatedLyrics);
      } catch (e) {
        // Silently fail - pinyin will be generated when user opens the song
        debugPrint('Background pinyin generation failed: $e');
      }
    });
  }

  @override
  Widget build(BuildContext context) {
    return Dialog(
      child: Container(
        constraints: const BoxConstraints(maxWidth: 500, maxHeight: 600),
        padding: const EdgeInsets.all(16),
        child: Column(
          mainAxisSize: MainAxisSize.min,
          crossAxisAlignment: CrossAxisAlignment.stretch,
          children: [
            // Header
            Row(
              children: [
                const Expanded(
                  child: Text(
                    'Add Song',
                    style: TextStyle(fontSize: 20, fontWeight: FontWeight.bold),
                  ),
                ),
                IconButton(
                  icon: const Icon(Icons.close),
                  onPressed: () => Navigator.pop(context),
                ),
              ],
            ),
            const SizedBox(height: 16),

            // Tabs
            TabBar(
              controller: _tabController,
              labelColor: primaryColor,
              tabs: const [
                Tab(text: 'Search'),
                Tab(text: 'Manual Entry'),
              ],
            ),
            const SizedBox(height: 16),

            // Tab content
            Expanded(
              child: TabBarView(
                controller: _tabController,
                children: [
                  _buildSearchTab(),
                  _buildManualTab(),
                ],
              ),
            ),
          ],
        ),
      ),
    );
  }

  Widget _buildSearchTab() {
    return Padding(
      padding: const EdgeInsets.only(top: 4),
      child: Column(
        mainAxisSize: MainAxisSize.min,
        crossAxisAlignment: CrossAxisAlignment.stretch,
        children: [
          // Input fields
          TextField(
          controller: _titleController,
          decoration: const InputDecoration(
            labelText: 'Song Title (in Chinese)',
            border: OutlineInputBorder(),
          ),
          onSubmitted: (_) => _searchSong(),
        ),
        const SizedBox(height: 12),
        TextField(
          controller: _artistController,
          decoration: const InputDecoration(
            labelText: 'Artist (optional)',
            border: OutlineInputBorder(),
          ),
          onSubmitted: (_) => _searchSong(),
        ),
        const SizedBox(height: 16),

        // Search button
        ElevatedButton.icon(
          onPressed: _isSearching ? null : _searchSong,
          icon: const Icon(Icons.search),
          label: Text(_isSearching ? 'Searching...' : 'Search'),
          style: ElevatedButton.styleFrom(
            backgroundColor: primaryColor,
            foregroundColor: Colors.white,
            padding: const EdgeInsets.symmetric(vertical: 12),
          ),
        ),

        // Error message
        if (_errorMessage != null) ...[
          const SizedBox(height: 12),
          Text(
            _errorMessage!,
            style: const TextStyle(color: Colors.red),
            textAlign: TextAlign.center,
          ),
        ],

        // Search results
        if (_searchResults.isNotEmpty) ...[
          const SizedBox(height: 16),
          const Text(
            'Select a version:',
            style: TextStyle(fontWeight: FontWeight.bold),
          ),
          const SizedBox(height: 8),
          Expanded(
            child: ListView.builder(
              shrinkWrap: true,
              itemCount: _searchResults.length,
              itemBuilder: (context, index) {
                final result = _searchResults[index];
                return Card(
                  child: ListTile(
                    title: Text(result['trackName'] ?? 'Unknown'),
                    subtitle: Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        Text('Artist: ${result['artistName'] ?? 'Unknown'}'),
                        if (result['albumName'] != null)
                          Text('Album: ${result['albumName']}'),
                      ],
                    ),
                    trailing: const Icon(Icons.add),
                    onTap: () => _addSong(result),
                  ),
                );
              },
            ),
          ),
        ],
      ],
      ),
    );
  }

  Widget _buildManualTab() {
    return Padding(
      padding: const EdgeInsets.only(top: 4),
      child: Column(
        mainAxisSize: MainAxisSize.min,
        crossAxisAlignment: CrossAxisAlignment.stretch,
        children: [
          TextField(
          controller: _titleController,
          decoration: const InputDecoration(
            labelText: 'Song Title',
            border: OutlineInputBorder(),
          ),
        ),
        const SizedBox(height: 12),
        TextField(
          controller: _artistController,
          decoration: const InputDecoration(
            labelText: 'Artist (optional)',
            border: OutlineInputBorder(),
          ),
        ),
        const SizedBox(height: 12),
        Expanded(
          child: TextField(
            controller: _lyricsController,
            decoration: const InputDecoration(
              labelText: 'Lyrics (paste here)',
              border: OutlineInputBorder(),
              hintText: 'Paste your lyrics here...',
            ),
            maxLines: null,
            expands: true,
            textAlignVertical: TextAlignVertical.top,
          ),
        ),
        const SizedBox(height: 16),

        // Add button
        ElevatedButton.icon(
          onPressed: _addManualSong,
          icon: const Icon(Icons.add),
          label: const Text('Add Song'),
          style: ElevatedButton.styleFrom(
            backgroundColor: primaryColor,
            foregroundColor: Colors.white,
            padding: const EdgeInsets.symmetric(vertical: 12),
          ),
        ),

        // Error message
        if (_errorMessage != null) ...[
          const SizedBox(height: 12),
          Text(
            _errorMessage!,
            style: const TextStyle(color: Colors.red),
            textAlign: TextAlign.center,
          ),
        ],
      ],
      ),
    );
  }
}
